idf_component_register(
    SRCS
        "sensor.c"
        "sensor_generic.c"
        "sensor_simulate.c"
        "sensor_transform.c"
        "drivers/drv_bme280.c"
        "drivers/drv_bmp280.c"
        "drivers/drv_qmi8658.c"
        "drivers/drv_tcs34725.c"
        "drivers/drv_as7341.c"
        "drivers/drv_vl53l1x.c"
        "drivers/drv_vl53l0x.c"
        "drivers/drv_tof_modules.c"
        "drivers/drv_gamepad.c"
        "drivers/drv_gpio.c"
        "drivers/drv_mcp3208.c"
        "drivers/drv_qre1113.c"
        "drivers/drv_ir_ball.c"
        "drivers/drv_vk36n16.c"
        "drivers/drv_m5_8angle.c"
        "drivers/drv_m5_step16.c"
        "drivers/drv_bmi270_bmm150.c"
        "drivers/drv_ina226.c"
        "drivers/drv_motor_ctrl_status.c"
    INCLUDE_DIRS "include"
    PRIV_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/main"
    REQUIRES bus_i2c bus_i2c3 bus_spi bus_uart i2c_mux esp_timer hid_host esp_adc esp_driver_gpio debug_flag imu
)
